server:
  port: 8080

spring:
  application:
    name: erm-service
  profiles:
    active: @spring.profiles.active@
  mvc:
    servlet:
      path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO


