spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ermdb
    username: admin
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false

# Feign Client
system:
  service:
    url: https://uaa-new.dev.apusplatform.com
department:
  service:
    url: https://resources-service.dev.apusplatform.com
  auth:
    token: Bearer Bearer eyJraWQiOiJlZGUzMThjZC1kZmIwLTQ2NDAtYjM4Zi03YzdkMmQzOTVkOGUiLCJhbGciOiJSUzI1NiJ9.eyJ0ZW5hbnRfaWQiOiIyMDEiLCJzdWIiOiJhcG9kaW9AZ21haWwuY29tIiwiaXNfb3duZXIiOnRydWUsImlzcyI6Imh0dHA6Ly8xMC4wLjEuMjA3OjgwODEiLCJhdXRob3JpdGllcyI6WyJNYW51ZmFjdG9yeSIsIkJMRE5NIl0sImF1ZCI6InRlc3QiLCJkZWZhdWx0X3RlbmFudF9pZCI6MjAxLCJuYmYiOjE3NTcyOTczNzcsImlzX3JlZ2lzdGVyIjp0cnVlLCJkZWZhdWx0X2Jpel9hcHBfaWQiOjEwLCJ1c2VyX2lkIjo1OCwib3JnX2lkIjozMDIsInNjb3BlIjpbImdhdGV3YXkiXSwiZGVmYXVsdF9vcmdfaWQiOjMzMDAsImV4cCI6MTc1ODE2MTM3NywiaWF0IjoxNzU3Mjk3Mzc3LCJqdGkiOiJhMTdjNzY5YS1jZjJmLTRmYjctOTc0OS02OTYzOTgyYmFhNjYifQ.h0g13Y29IN6p7VQiW_WmY9yaOrTFF0NfZMR2IMqPhmS1ymaQsF8ZpqSH8sBEu_GQT3CYq-VVAKROXIuFgJ3Flu7b0zOd_c-xdetiY_K7rHg8WvoqsOQ7HNmxxFoca7_9kveqGrw_nAlTOuC9eeR35QbvCKKAB8SGNXVm_O983iAPvn2rUoVWt9XkVuicZA1E0Y8a1ahZzOC9T_W6VK8IySnOH6JgxRql021aapYiuYBJLRXmsPUUHIdfKiORM4bbaNnjmN0qQQ5aIXfCJrdpkXlm-tryPZB_r3CwhR0ePFzWa_E_4uApIL1LzRYbT63BRUziQJsAXdlgcq6t-HAwLQ
    tenantId: 201
employee:
  service:
    url: https://reactive-erp-gateway.dev.apusplatform.com/services/resources
  auth:
    token: Bearer eyJraWQiOiJlZGUzMThjZC1kZmIwLTQ2NDAtYjM4Zi03YzdkMmQzOTVkOGUiLCJhbGciOiJSUzI1NiJ9.eyJ0ZW5hbnRfaWQiOiIyMDEiLCJzdWIiOiJzeXN0ZW1fYWRtaW4iLCJpc19vd25lciI6ZmFsc2UsImlzcyI6Imh0dHA6Ly8xMC4wLjEuMjA3OjgwODEiLCJhdXRob3JpdGllcyI6WyIzMzMzMyIsInR0dCIsIlFMbHZlMSIsIlNZU1RFTV9BRE1JTiJdLCJhdWQiOiJ0ZXN0IiwiZGVmYXVsdF90ZW5hbnRfaWQiOjIwMSwibmJmIjoxNzU3MzkwMTQwLCJpc19yZWdpc3RlciI6dHJ1ZSwiZGVmYXVsdF9iaXpfYXBwX2lkIjoxLCJ1c2VyX2lkIjoxLCJvcmdfaWQiOjMwMiwic2NvcGUiOlsiZ2F0ZXdheSJdLCJkZWZhdWx0X29yZ19pZCI6MSwiZXhwIjoxNzU4MjU0MTQwLCJpYXQiOjE3NTczOTAxNDAsImp0aSI6IjQzZjYyMjFkLTAzMzEtNDRiYy05NzUzLTBhZjVmMjM1M2M2OCJ9.Rm7qrkkUQEzBq8xOMf_qaO_CmDKYIjk3P5C6bEBoDl3-CDFz6kGfAjgRjPZD1EvVBvxwL9WkOf05paYKvWaL5nk66DapCsGWWAXxW_iMG6f1GbeGbEwgb1xDf62cyrT71fGVecA-O2GxazsE_jed9f3Z5DGTv6CuV-PecuKmmT4CHluzW8XMxGXzfiHU9vrnqO-w8y_20L9QQU7hLSiA_k67UI7kGi3h9yV5rzcTj6VpejhP9TDPUq4IP6bDqSCrCCzlAnzXWquKF8F-NlrYnrwu3UjzW1Q60JMvIEEEH2PX80id58fhZ5RsAOao9H9xcW1eVdcQbdrNbvXuZ8FXVQ
    domain: apodio.dev.apusplatform.com

cloudinary:
  cloud-name: dk0afqj7n
  api-key: 497543569276558
  api-secret: jq3Ij6a2Kzi14aidQC1iyd3XLmk


# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: erm-service
    server: http://localhost:${server.port}/api/v1
    title: Erm service
    version: 1.0.0